# Folders containing collision_failures.pkl and failure_summary.csv
# Supports absolute path or path relative to this file.
log_dirs:
  - "../train_SAC/eval_logs/random_eval_0311-5"
  - "../train_SAC/eval_logs/random_eval_0311-6"
  - "../train_SAC/eval_logs/random_eval_0311-7"
  - "../train_SAC/eval_logs/random_eval_0311-8"

# Optional output dir for aggregated stats
output_dir: "./offline_states_logs/offline_stats"

