# Folders containing collision_failures.pkl and failure_summary.csv
# Supports absolute path or path relative to this file.
log_dirs:
#  - "../train_SAC/eval_logs/random_eval_0311-1"
#  - "../train_SAC/eval_logs/random_eval_0311-2"
#  - "../train_SAC/eval_logs/random_eval_0311-3"
#  - "../train_SAC/eval_logs/random_eval_0311-4"
#  - "../train_SAC/eval_logs/random_eval_0311-5"
#  - "../train_SAC/eval_logs/random_eval_0311-6"
#  - "../train_SAC/eval_logs/random_eval_0311-7"
#  - "../train_SAC/eval_logs/random_eval_0311-8"
#  - "../train_SAC/eval_logs/random_eval_0311-9-withnofailure"
#  - "../train_SAC/eval_logs/fake_from_train_0311_1"
  - "../train_SAC/eval_logs/sac_eval_0313"
  - "../train_SAC/eval_logs/sac_eval_0313-1"
  - "../train_SAC/eval_logs/sac_eval_0313-2"

# Optional output dir for aggregated stats
output_dir: "./offline_states_logs/sac-0312-rew1-preload"

# When consecutive fail+stuck frames appear, keep only the first K fail frames,
# discard later fail+stuck frames until a non-stuck/fail frame appears.
# 0 means do not trim.
consecutive_fail_keep_k: 0

