#policy: "sac_0312-rew1-preload"  # random表示随机策略，其余情况下则查找训练好的模型
#checkpoint: "checkpoint_step_40000"

policy: "random"
checkpoint: ""

#policy: "sac_0310-rew2"  # random表示随机策略，其余情况下则查找训练好的模型
#checkpoint: "checkpoint_step_22000"

go2_task: "terrain"
go2_config: "go2_2.yaml"
terrain_config: "terrain_config.yaml"

episodes: 4000

max_episode_steps: 35
seed: 1

log_name: "nohup_random_eval_go2-2_1"
#log_name: "random_eval_0311-4"
#log_name: "sac_eval_0313-2"

use_curr_force: False  # 强制使用当前配置

render: False
save_non_failure_trajectories: True

# nohup python deploy/deploy_mujoco_go2/train_SAC/eval.py >nohup_policy_eval_sac_0310_rew2_21000.out 2>&1 &
# nohup python deploy/deploy_mujoco_go2/train_SAC/eval.py >nohup_policy_eval_sac_0310_rew2_22000.out 2>&1 &

# nohup python deploy/deploy_mujoco_go2/train_SAC/eval.py >nohup_random_eval_go2-2_1.out 2>&1 &
# nohup python deploy/deploy_mujoco_go2/train_SAC/eval.py >nohup_sac_eval.out 2>&1 &
