go2_task: "terrain"
go2_config: "go2.yaml"
terrain_config: "terrain_config.yaml"

total_timesteps: 80000
max_episode_steps: 350

# Device / Torch runtime
# auto | cpu | cuda | cuda:0
device: "cuda:2"
seed: 0
torch_deterministic: false
cudnn_benchmark: true
allow_tf32: true
torch_num_threads: 0

# SAC-dense hyperparameters
learning_starts: 10000
learning_rate: 0.0001
batch_size: 256
buffer_size: 1000000
train_freq: 1
gradient_steps: 1
tau: 0.005
gamma: 0.99

# Dense replay filter threshold
reward_threshold: 8.0

# Non-finite obs clamp to avoid NaN propagation into actor
obs_abs_clip: 1000.0

# Plotting
# Save partial curves every N timesteps.
plot_save_every_steps: 2000
# Moving average window for reward smoothing.
plot_smooth_window: 20

dense_sample_ratio: 0.7

log_name: "sac_dense_0310-rew2-ratio70"
#log_name: "debug"

#nohup python deploy/deploy_mujoco_go2/train_SAC_dense/train.py >nohup_sac_dense_0310-rew2-ratio70.out 2>&1 &
